### ISSUE TITLE
Question about the `pack!` macro, using pack! in multiple files?

### ISSUE THREAD

**Issue by shaunsingh** [datwaft/nvim.conf#15]
First of all, thank you for all of the macros!

I see that your pack! macro should add packages to the global compile-time variable `conf/pack`. From what I understand, this means I *should* be able to add `(pack!` statements in multiple files, as long as those files are `required` before `unpack!` is ran. However,  when I use `pack!` in other files, require those files, then call `unpack!` the packages declarations are loaded to packer.nvim. I was wondering how should I go about doing this

**Comment by datwaft** [comment]
Indeed, it theory it should be possible, but I haven't tried it yet.

Are you using Aniseed or Hotpot?

If you are using Hotpot, see https://github.com/rktjmp/hotpot.nvim/issues/38. In this issue I wanted to do a similar thing, and it was later on fixed, so you shouldn't have any problem in relation with that if you are using Hotpot, at least.

If you are using Hotpot and it doesn't work try doing something similar to what I did in that issue, so that we can know if it's a bug.

If you are using Aniseed it used to work when I used it, but I haven't used Aniseed since a long time ago.

**Comment by shaunsingh** [comment]
I am currently using hotpot, and just to test I tried it both with hotpot and aniseed. It doesn't work with either plugin, might be an issue with my code. 

For reference, I have configs organized in "modules" e.g. https://github.com/shaunsingh/nyoom.nvim/tree/module-rewrite/fnl/conf/modules/telescope, and packages are added in their respective pack.fnl files: https://github.com/shaunsingh/nyoom.nvim/blob/module-rewrite/fnl/conf/modules/telescope/pack.fnl. https://github.com/shaunsingh/nyoom.nvim/blob/module-rewrite/fnl/conf/init.fnl then requires each module and at the end I send `(unpack!)`

I tried the workarounds you did in the issue linked above (by doing whatever was in this comment: https://github.com/rktjmp/hotpot.nvim/issues/38#issuecomment-927129695) but same error in the end. I'll try manually compiling them and seeing if it makes any difference

**Comment by datwaft** [comment]
Can you show me the compilation result? (The Lua code that hotpot caches). In the README of the hotpot repository are some commands that give you the path of the current file in Lua code.

I will make some tests in the evening of today or tomorrow, when I find time.

**Comment by shaunsingh** [comment]
the `pack.fnl` file compiles to `return nil`

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/71196912/153960613-d5880d05-60da-4f51-9f19-40280efb93e1.png">

<img width="1402" alt="image" src="https://user-images.githubusercontent.com/71196912/153960707-e9ee50d9-9cce-4a02-9ade-59ccf36239bb.png">

`init.fnl` compiles to pretty much the same.

**Comment by datwaft** [comment]
I did a quick test with the following files:

```fennel
; init.fnl
(import-macros {: add-visited-module
                : print-global-variable} :macro)

(require :module)
(add-visited-module "init")

(print-global-variable)
```

```fennel
; module.fnl
(import-macros {: add-visited-module} :macro)

(add-visited-module "module")
```

```fennel
; macro.fnl
;; This global variable is a list of visited modules
(global global-variable [])

(fn add-visited-module [module-name]
  (table.insert global-variable module-name))

(fn print-global-variable []
  `(each [_# module-name# (ipairs ,global-variable)]
     (print (string.format "The module '%s' has been loaded." module-name#))))

{: add-visited-module
 : print-global-variable}
```

As you can see in the following code fragment, it seems to be a problem with Fennel itself and not with hotpot or aniseed. Maybe you can open an issue to see if it can be fixed.

```console
foo@bar:~$ fennel init.fnl
The module 'init' has been loaded.
